### ISSUE TITLE
启动logproxy后，浏览网页看不到log信息

### ISSUE THREAD

**Issue by litten** [unbug/logproxy#1]
![2015-04-13 10 34 23](https://cloud.githubusercontent.com/assets/2024949/7109061/ba8e6264-e1c8-11e4-8f46-b3152f70a8d3.png)

你好，我直接执行logproxy命令后，用chrome浏览网页，控制台里看不到任何log信息，请问会是什么问题？还需要其他配置吗？谢谢。

**Comment by unbug** [comment]
你需要设置代理，如，你要查看iPhone的日志：你设置你的iPhone 的代理到`10.70.60.151`端口号`1630`

**Comment by litten** [comment]
好的，谢谢回答。

跟我想象中有点不一样，我以为是有自动设置web代理的方法了~
因为我们之前有做过一个类似的：https://github.com/rehorn/livepool
痛点就是得手工设置代理

**Comment by unbug** [comment]
你可以试试node调用CMD将tcpdump到一个固定的日志文件，在node里watch那个文件，然后再解析到livepool，可能就是权限和不好跨平台，你研究好了更新livepool给大家
